services:

  backend:
    build:
      context: ./Backend
      dockerfile: dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend
      dockerfile: dockerfile
    container_name: frontend
    ports:
      - "80:80"
    restart: unless-stopped
